// src/constants/airportTransferLocations.js

module.exports = Object.freeze([
  // Airport
  {
    id: 1,
    type: "airport",
    name: "Veer Savarkar International Airport",
    address: "Port Blair",
    lat: 11.6412,
    lng: 92.7297,
  },

  // Jetties
  {
    id: 2,
    type: "jetty",
    name: "Phoenix Bay Jetty",
    address: "Port Blair",
    lat: 11.6698,
    lng: 92.7474,
  },
  {
    id: 3,
    type: "jetty",
    name: "Haddo Jetty",
    address: "Port Blair",
    lat: 11.6843,
    lng: 92.7393,
  },
  {
    id: 4,
    type: "jetty",
    name: "Junglighat Jetty",
    address: "Port Blair",
    lat: 11.6569,
    lng: 92.7387,
  },
  {
    id: 5,
    type: "jetty",
    name: "Neil Island Jetty",
    address: "Shaheed Dweep",
    lat: 11.8318,
    lng: 93.0417,
  },
  {
    id: 6,
    type: "jetty",
    name: "Havelock Jetty",
    address: "Swaraj Dweep",
    lat: 11.9683,
    lng: 92.9998,
  },

  // Hotels
  {
    id: 10,
    type: "hotel",
    name: "SeaShell Port Blair",
    address: "Marine Hill, Port Blair",
    lat: 11.6676,
    lng: 92.7479,
  },
  {
    id: 11,
    type: "hotel",
    name: "SeaShell Havelock",
    address: "Govind Nagar, Swaraj Dweep",
    lat: 11.9841,
    lng: 92.9604,
  },
  {
    id: 12,
    type: "hotel",
    name: "Silver Sand Beach Resort",
    address: "Vijaynagar Beach, Swaraj Dweep",
    lat: 11.9966,
    lng: 92.9824,
  },
  {
    id: 13,
    type: "hotel",
    name: "Barefoot at Havelock",
    address: "Radhanagar Beach",
    lat: 11.9846,
    lng: 92.9453,
  },
  {
    id: 14,
    type: "hotel",
    name: "Symphony Samudra",
    address: "Chidiya Tapu Road, Port Blair",
    lat: 11.5488,
    lng: 92.7047,
  },
  {
    id: 15,
    type: "hotel",
    name: "TSG Blue Resort",
    address: "Govind Nagar, Swaraj Dweep",
    lat: 11.9825,
    lng: 92.9642,
  },
  {
    id: 16,
    type: "hotel",
    name: "Coral Reef Resort",
    address: "Swaraj Dweep",
    lat: 11.9827,
    lng: 92.9701,
  },

  // Restaurants
  {
    id: 20,
    type: "restaurant",
    name: "Anju Coco Resto",
    address: "Govind Nagar, Swaraj Dweep",
    lat: 11.9828,
    lng: 92.9655,
  },
  {
    id: 21,
    type: "restaurant",
    name: "Full Moon Cafe",
    address: "Beach No. 5, Swaraj Dweep",
    lat: 11.9914,
    lng: 92.9811,
  },
  {
    id: 22,
    type: "restaurant",
    name: "New Lighthouse Restaurant",
    address: "Port Blair",
    lat: 11.6687,
    lng: 92.7465,
  },
  {
    id: 23,
    type: "restaurant",
    name: "Something Different",
    address: "Neil Island",
    lat: 11.8315,
    lng: 93.0388,
  },

  // Attractions
  {
    id: 30,
    type: "attraction",
    name: "Cellular Jail",
    address: "Port Blair",
    lat: 11.6738,
    lng: 92.7522,
  },
  {
    id: 31,
    type: "attraction",
    name: "Corbyn's Cove Beach",
    address: "Port Blair",
    lat: 11.6483,
    lng: 92.7494,
  },
  {
    id: 32,
    type: "attraction",
    name: "Radhanagar Beach",
    address: "Swaraj Dweep",
    lat: 11.9849,
    lng: 92.9472,
  },
  {
    id: 33,
    type: "attraction",
    name: "Elephant Beach",
    address: "Swaraj Dweep",
    lat: 12.0042,
    lng: 92.9555,
  },
  {
    id: 34,
    type: "attraction",
    name: "Bharatpur Beach",
    address: "Shaheed Dweep",
    lat: 11.8426,
    lng: 93.0373,
  },
  {
    id: 35,
    type: "attraction",
    name: "Natural Bridge",
    address: "Shaheed Dweep",
    lat: 11.8135,
    lng: 93.0282,
  },
]);
