module.exports = Object.freeze([
  {
    id: 1,
    type: "hotel",
    name: "TSG Aura Resort",
    address:
      "Beach No. 5, Sitapur Beach, Shaheed Dweep (Neil Island), Port Blair, South Andaman, Andaman and Nicobar Islands, India – 744104",
    lat: 11.8207788,
    lng: 93.0609772,
    place: "neil island",
  },
  {
    id: 2,
    type: "hotel",
    name: "Symphony Summer Sands, Neil Island",
    address:
      "Ram Nagar Beach, Ram Nagar, Shaheed Dweep (Neil Island), Port Blair, South Andaman, Andaman and Nicobar Islands, India – 744104",
    lat: 11.8158,
    lng: 93.0481,
    place: "neil island",
  },
  {
    id: 3,
    type: "hotel",
    name: "Tango Beach Resort",
    address:
      "Beach No. 1, Lakshmanpur Beach, Shaheed Dweep (Neil Island), Port Blair, South Andaman, Andaman and Nicobar Islands, India – 744104",
    lat: 11.8329,
    lng: 93.0135,
    place: "neil island",
  },
  {
    id: 4,
    type: "hotel",
    name: "Pearl Park Beach Resort & SPA",
    address:
      "Beach No. 1, Lakshmanpur Beach, Shaheed Dweep (Neil Island), Port Blair, South Andaman, Andaman and Nicobar Islands, India – 744104",
    lat: 11.8327,
    lng: 93.0118,
    place: "neil island",
  },
  {
    id: 5,
    type: "attraction",
    name: "Bharatpur Beach",
    address: "Bharatpur, Shaheed Dweep (Neil Island)",
    lat: 11.84116,
    lng: 93.03133,
    place: "neil island",
  },
  {
    id: 6,
    type: "attraction",
    name: "Laxmanpur Beach I",
    address: "Laxmanpur Village, Shaheed Dweep",
    lat: 11.83338,
    lng: 93.01295,
    place: "neil island",
  },
  {
    id: 7,
    type: "attraction",
    name: "Laxmanpur Beach II (Natural Bridge)",
    address: "Laxmanpur Village, Shaheed Dweep",
    lat: 11.82485,
    lng: 93.00886,
    place: "neil island",
  },
  {
    id: 8,
    type: "attraction",
    name: "Natural Bridge (Howrah Bridge)",
    address: "Laxmanpur Beach II",
    lat: 11.8249,
    lng: 93.0087,
    place: "neil island",
  },
  {
    id: 9,
    type: "attraction",
    name: "Sitapur Beach (Sunrise Beach)",
    address: "Sitapur Village, Shaheed Dweep",
    lat: 11.82069,
    lng: 93.06125,
    place: "neil island",
  },
  {
    id: 10,
    type: "attraction",
    name: "Ram Nagar Beach",
    address: "Ram Nagar, Shaheed Dweep",
    lat: 11.8158,
    lng: 93.0481,
    place: "neil island",
  },
  {
    id: 11,
    type: "attraction",
    name: "Neil Kendra Village",
    address: "Neil Kendra, Shaheed Dweep",
    lat: 11.82782,
    lng: 93.03477,
    place: "neil island",
  },
  //  {
  //    "id": 12,
  //    "type": "jetty",
  //    "name": "Neil Island Jetty",
  //    "address": "Neil Kendra, Shaheed Dweep",
  //    "lat": 11.82674,
  //    "lng": 93.03622,
  //    "place": "neil island"
  //  },
  {
    id: 13,
    type: "attraction",
    name: "Neil Island Market",
    address: "Neil Kendra",
    lat: 11.82757,
    lng: 93.03492,
    place: "neil island",
  },
  {
    id: 14,
    type: "attraction",
    name: "Vegetable Farms (Organic Farms)",
    address: "Neil Kendra & surrounding villages",
    lat: 11.8286,
    lng: 93.0349,
    place: "neil island",
  },
  {
    id: 15,
    type: "hotel",
    name: "Taj Exotica Resort & Spa, Andamans",
    address:
      "Radha Nagar, Beach Number 7, Havelock Island, Andaman and Nicobar Islands 744211",
    lat: 11.984243,
    lng: 92.956863,
    place: "havelock-island",
  },
  {
    id: 16,
    type: "hotel",
    name: "TSG Blue Resort & Spa",
    address:
      "Radha Nagar, Beach Number 7, Havelock Island, Andaman and Nicobar Islands 744211",
    lat: 11.989714,
    lng: 92.954893,
    place: "havelock-island",
  },
  {
    id: 17,
    type: "hotel",
    name: "Barefoot at Havelock",
    address:
      "Beach No. 7, Radhanagar Village, Havelock Island, Andaman and Nicobar Islands 744211",
    lat: 11.986947,
    lng: 92.948328,
    place: "havelock-island",
  },
  {
    id: 18,
    type: "hotel",
    name: "De Foret",
    address:
      "No. 7, Radha Nagar Village, Swaraj Dweep, Andaman and Nicobar Islands 744211",
    lat: 12.0047102,
    lng: 92.9597832,
    place: "havelock-island",
  },
  {
    id: 19,
    type: "hotel",
    name: "Symphony Palms Beach Resort & Spa",
    address:
      "Beach No. 3, Govind Nagar, Havelock, Andaman and Nicobar Islands 744211",
    lat: 11.968,
    lng: 92.99011,
    place: "havelock-island",
  },
  {
    id: 20,
    type: "hotel",
    name: "Dolphin Beach Resort",
    address:
      "No. 5, Govind Nagar, Havelock Island (Swaraj Dweep), Andaman and Nicobar Islands 744211",
    lat: 11.9678,
    lng: 93.0035,
    place: "havelock-island",
  },
  {
    id: 21,
    type: "hotel",
    name: "Sea Shell Resort",
    address: "No. 2, Govind Nagar, Andaman and Nicobar Islands 744211",
    lat: 11.9675,
    lng: 92.9902,
    place: "havelock-island",
  },
  {
    id: 22,
    type: "hotel",
    name: "Silver Sand Beach Resort, Havelock",
    address:
      "No. 5, Vijay Nagar Beach, Swaraj Dweep (Havelock Island), Andaman and Nicobar Islands 744211",
    lat: 12.0104239,
    lng: 93.0068355,
    place: "havelock-island",
  },
  {
    id: 23,
    type: "hotel",
    name: "Tilar Siro",
    address:
      "Beach No. 5, Vijay Nagar, Swaraj Dweep (Havelock Island), Andaman and Nicobar Islands 744211",
    lat: 11.9672,
    lng: 92.9984,
    place: "havelock-island",
  },
  {
    id: 24,
    type: "hotel",
    name: "Aquays Hotels & Resorts",
    address:
      "Beach No. 5, Govind Nagar, Havelock Island (Swaraj Dweep), Andaman and Nicobar Islands 744211",
    lat: 11.9806,
    lng: 92.9839,
    place: "havelock-island",
  },
  {
    id: 25,
    type: "hotel",
    name: "Coral Reef Resort & Spa, Havelock",
    address:
      "No. 5, Vijayanagar, Swaraj Dweep (Havelock Island), South Andaman District, Andaman and Nicobar Islands 744211",
    lat: 12.0169,
    lng: 93.0078,
    place: "havelock-island",
  },
  {
    id: 26,
    type: "hotel",
    name: "Sandyy Wavess Beach Resort",
    address: "5 Vijay Nagar, Govind Nagar, Andaman and Nicobar Islands 744211",
    lat: 12.0107,
    lng: 93.0066,
    place: "havelock-island",
  },
  {
    id: 27,
    type: "hotel",
    name: "Ocean Tree Beach Resort & Spa",
    address: "Beach No. 5, Havelock Island, Andaman and Nicobar Islands 744211",
    lat: 12.0165,
    lng: 93.0077,
    place: "havelock-island",
  },
  {
    id: 28,
    type: "attraction",
    name: "Radhanagar Beach (Beach No. 7)",
    address: "Radhanagar, Swaraj Dweep",
    lat: 11.9846,
    lng: 92.9552,
    place: "havelock-island",
  },
  {
    id: 29,
    type: "attraction",
    name: "Elephant Beach",
    address: "West Coast, Swaraj Dweep",
    lat: 12.0067,
    lng: 92.9647,
    place: "havelock-island",
  },
  {
    id: 30,
    type: "attraction",
    name: "Kalapathar Beach",
    address: "Kalapathar Village, Swaraj Dweep",
    lat: 11.9478,
    lng: 93.0286,
    place: "havelock-island",
  },
  {
    id: 31,
    type: "attraction",
    name: "Vijaynagar Beach (Beach No. 5)",
    address: "Vijaynagar, Swaraj Dweep",
    lat: 12.0105,
    lng: 93.0068,
    place: "havelock-island",
  },
  {
    id: 32,
    type: "attraction",
    name: "Govind Nagar Beach (Beach No. 3)",
    address: "Govind Nagar",
    lat: 11.9682,
    lng: 92.991,
    place: "havelock-island",
  },
  {
    id: 33,
    type: "attraction",
    name: "Nemo Reef",
    address: "Govind Nagar Beach",
    lat: 11.9686,
    lng: 92.9918,
    place: "havelock-island",
  },
  {
    id: 34,
    type: "attraction",
    name: "Mangrove Kayaking Point",
    address: "Havelock Mangroves",
    lat: 11.9819,
    lng: 92.9989,
    place: "havelock-island",
  },
  {
    id: 35,
    type: "attraction",
    name: "Lighthouse (Elephant Beach side)",
    address: "Northern Havelock",
    lat: 12.0156,
    lng: 92.9728,
    place: "havelock-island",
  },
  // {
  //   "id": 36,
  //   "type": "jetty",
  //   "name": "Havelock Jetty",
  //   "address": "Govind Nagar, Swaraj Dweep",
  //   "lat": 11.9849,
  //   "lng": 92.9873,
  //   "place": "havelock-island"
  // },
  {
    id: 36,
    type: "jetty",
    name: "Makruzz Ferry Terminal",
    address: "Havelock Jetty",
    lat: 11.9849,
    lng: 92.9873,
    place: "havelock-island",
  },
  {
    id: 37,
    type: "jetty",
    name: "Green Ocean Ferry Terminal",
    address: "Havelock Jetty",
    lat: 11.9849,
    lng: 92.9873,
    place: "havelock-island",
  },
  {
    id: 38,
    type: "attraction",
    name: "Havelock Market",
    address: "Govind Nagar",
    lat: 11.9842,
    lng: 92.9878,
    place: "havelock-island",
  },
  {
    id: 39,
    type: "attraction",
    name: "Govind Nagar Junction",
    address: "Govind Nagar",
    lat: 11.9766,
    lng: 92.9897,
    place: "havelock-island",
  },
  {
    id: 40,
    type: "attraction",
    name: "Blue Planet Scuba",
    address: "Govind Nagar",
    lat: 11.9683,
    lng: 92.9913,
    place: "havelock-island",
  },
  {
    id: 41,
    type: "attraction",
    name: "Dive India",
    address: "Govind Nagar",
    lat: 11.9681,
    lng: 92.9911,
    place: "havelock-island",
  },
  {
    id: 42,
    type: "attraction",
    name: "Barefoot Scuba",
    address: "Radhanagar",
    lat: 11.9865,
    lng: 92.9491,
    place: "havelock-island",
  },
  {
    id: 43,
    type: "attraction",
    name: "Ocean Tribe Dive Centre",
    address: "Govind Nagar",
    lat: 11.968,
    lng: 92.9908,
    place: "havelock-island",
  },
  {
    id: 44,
    type: "attraction",
    name: "ScubaLov Dive Centre",
    address: "Govind Nagar",
    lat: 11.9684,
    lng: 92.9916,
    place: "havelock-island",
  },
  {
    id: 45,
    type: "attraction",
    name: "Dive Andaman",
    address: "Govind Nagar",
    lat: 11.9691,
    lng: 92.9922,
    place: "havelock-island",
  },
  {
    id: 46,
    type: "attraction",
    name: "Havelock Bus Stand",
    address: "Govind Nagar",
    lat: 11.9838,
    lng: 92.9875,
    place: "havelock-island",
  },
  {
    id: 47,
    type: "attraction",
    name: "Forest Check Post (Elephant Beach Trek)",
    address: "Near Radhanagar Road",
    lat: 11.9955,
    lng: 92.9733,
    place: "havelock-island",
  },
  {
    id: 48,
    type: "attraction",
    name: "Elephant Beach Trek Entry",
    address: "Havelock Forest Road",
    lat: 11.997,
    lng: 92.9742,
    place: "havelock-island",
  },
  {
    id: 49,
    type: "attraction",
    name: "Beach No. 1",
    address: "Near Jetty",
    lat: 11.9848,
    lng: 92.9876,
    place: "havelock-island",
  },
  {
    id: 50,
    type: "attraction",
    name: "Beach No. 2",
    address: "Govind Nagar",
    lat: 11.9768,
    lng: 92.989,
    place: "havelock-island",
  },
  {
    id: 51,
    type: "attraction",
    name: "Beach No. 3",
    address: "Govind Nagar",
    lat: 11.9682,
    lng: 92.991,
    place: "havelock-island",
  },
  {
    id: 52,
    type: "attraction",
    name: "Beach No. 5",
    address: "Vijaynagar",
    lat: 12.0105,
    lng: 93.0068,
    place: "havelock-island",
  },
  {
    id: 53,
    type: "attraction",
    name: "Beach No. 7 (Radhanagar Beach)",
    address: "Radhanagar",
    lat: 11.9846,
    lng: 92.9552,
    place: "havelock-island",
  },
  {
    id: 54,
    type: "hotel",
    name: "Haywizz Havelock Island Resort",
    address:
      "No. 1, Govind Nagar, Havelock Island (Swaraj Dweep), Port Blair Tehsil, South Andaman District, Andaman and Nicobar Islands 744211",
    lat: 11.9722,
    lng: 92.9904,
    place: "havelock-island",
  },
]);
