const locations = [
  {
    id: 1,
    place_types: ["airport"],
    name: "Veer Savarkar International Airport (VSI Airport)",
    address:
      "Lamba Line, Sri Vijaya Puram, Andaman and Nicobar Islands 744103, India",
    lat: 11.641656,
    lng: 92.730243,
    place: "port-blair",
  },
  {
    id: 2,
    place_types: ["attraction"],
    name: "Wandoor Beach",
    address: "Wandoor Beach, SH8, Andaman and Nicobar Islands 744103, India",
    lat: 11.5957905,
    lng: 92.6079007,
    place: "port-blair",
  },
  {
    id: 3,
    place_types: ["attraction"],
    name: "Chidiya Tapu Beach",
    address:
      "Chidiya Tapu Beach, Sri Vijaya Puram, Andaman and Nicobar Islands 744105, India",
    lat: 11.5059682,
    lng: 92.7014649,
    place: "port-blair",
  },
  {
    id: 4,
    place_types: ["attraction"],
    name: "Aberdeen Bazaar",
    address:
      "Aberdeen Bazar, Aberdeen, Sri Vijaya Puram, Andaman and Nicobar Islands 744101, India",
    lat: 11.6675019,
    lng: 92.7412765,
    place: "port-blair",
  },
  {
    id: 5,
    place_types: ["attraction"],
    name: "Flag Point",
    address:
      "Near Flag Point, Sri Vijaya Puram, Andaman and Nicobar Islands, India",
    lat: 11.666078,
    lng: 92.754132,
    place: "port-blair",
  },
  {
    id: 6,
    place_types: ["attraction"],
    name: "Mount Harriet National Park",
    address:
      "Hope Town, Sri Vijaya Puram, Andaman and Nicobar Islands 744107, India",
    lat: 11.7201967,
    lng: 92.7334546,
    place: "port-blair",
  },
  {
    id: 7,
    place_types: ["attraction"],
    name: "Cellular Jail National Memorial",
    address:
      "Atlanta Point, Sri Vijaya Puram, Andaman and Nicobar Islands 744104, India",
    lat: 11.6747447,
    lng: 92.7478601,
    place: "port-blair",
  },
  {
    id: 8,
    place_types: ["attraction"],
    name: "Jogger's Park",
    address:
      "AHW Colony, Shadipur, Sri Vijaya Puram, Andaman and Nicobar Islands 744106, India",
    lat: 11.6569162,
    lng: 92.741523,
    place: "port-blair",
  },
  {
    id: 9,
    place_types: ["attraction"],
    name: "Marina Park",
    address:
      "Rajiv Gandhi Nagar, Sri Vijaya Puram, Andaman and Nicobar Islands 744104, India",
    lat: 11.6698312,
    lng: 92.7474232,
    place: "port-blair",
  },
  {
    id: 10,
    place_types: ["attraction"],
    name: "Gandhi Park",
    address:
      "AHW Colony, Shadipur, Sri Vijaya Puram, Andaman and Nicobar Islands 744101, India",
    lat: 11.6638498,
    lng: 92.7429775,
    place: "port-blair",
  },
  {
    id: 11,
    place_types: ["restaurant"],
    name: "Icy Spicy - Pure Veg",
    address:
      "Police Gurudwara Building, Aberdeen Bazar, Rajiv Gandhi Nagar, Sri Vijaya Puram, Andaman and Nicobar Islands 744101, India",
    lat: 11.6690586,
    lng: 92.7427059,
    place: "port-blair",
  },
  {
    id: 12,
    place_types: ["restaurant"],
    name: "Annapurna Cafeteria Pure Veg",
    address:
      "71, MA Rd, opp. Model School, Aberdeen Bazar, Rajiv Gandhi Nagar, Sri Vijaya Puram, Andaman and Nicobar Islands 744101, India",
    lat: 11.6671159,
    lng: 92.7423254,
    place: "port-blair",
  },
  {
    id: 13,
    place_types: ["restaurant"],
    name: "Prabha's Manasara Pure Veg",
    address:
      "112, MG Road, Lamba Line, Sri Vijaya Puram, Andaman and Nicobar Islands 744103, India",
    lat: 11.6485166,
    lng: 92.7316133,
    place: "port-blair",
  },
  {
    id: 14,
    place_types: ["restaurant"],
    name: "Amaya",
    address:
      "Sea Shell, Marine Hill, Sri Vijaya Puram, Andaman and Nicobar Islands 744104, India",
    lat: 11.6759133,
    lng: 92.7396199,
    place: "port-blair",
  },
  {
    id: 15,
    place_types: ["restaurant"],
    name: "Mavi Rooftop Lounge",
    address:
      "TSG Emerald View, #25, Maulana Azad Road, Phoenix Bay, Sri Vijaya Puram, Andaman and Nicobar Islands 744102, India",
    lat: 11.6685451,
    lng: 92.7313026,
    place: "port-blair",
  },
  {
    id: 16,
    place_types: ["restaurant"],
    name: "New Lighthouse Restaurant",
    address:
      "Rajiv Gandhi Nagar, Sri Vijaya Puram, Andaman and Nicobar Islands 744104, India",
    lat: 11.6716483,
    lng: 92.7465883,
    place: "port-blair",
  },
  {
    id: 17,
    place_types: ["restaurant"],
    name: "Sinclairs Bayview",
    address:
      "Corbyns Cove Rd, South Point, Shadipur, Sri Vijaya Puram, Andaman and Nicobar Islands 744106, India",
    lat: 11.6638864,
    lng: 92.7556765,
    place: "port-blair",
  },
  {
    id: 18,
    place_types: ["restaurant"],
    name: "Deliciaa's Grillax",
    address:
      "Housing Colony, Bhathu Basti, Sri Vijaya Puram, Andaman and Nicobar Islands 744105, India",
    lat: 11.6233598,
    lng: 92.7160692,
    place: "port-blair",
  },
  {
    id: 19,
    place_types: ["restaurant"],
    name: "Jamun Cove - Beachfront",
    address:
      "Corbyns Cove Rd, Carbyns Cove, Sri Vijaya Puram, Andaman and Nicobar Islands 744101, India",
    lat: 11.6427867,
    lng: 92.7467246,
    place: "port-blair",
  },
  {
    id: 20,
    place_types: ["restaurant"],
    name: "Lazeez Rooftop Restaurant",
    address:
      "3rd Floor, Hotel Sand Heaven, opp. Airport, Lamba Line, Sri Vijaya Puram, Andaman and Nicobar Islands 744105, India",
    lat: 11.6514648,
    lng: 92.731391,
    place: "port-blair",
  },
  {
    id: 21,
    place_types: ["hotel"],
    name: "Symphony Samudra Beachside Jungle Resort And Spa",
    address:
      "Chidyatapu Beach, next to Biological Park, Sri Vijaya Puram, Andaman and Nicobar Islands 744105, India",
    lat: 11.5080247,
    lng: 92.7039744,
    place: "port-blair",
  },
  {
    id: 22,
    place_types: ["hotel"],
    name: "Sea Cliff",
    address:
      "South Point, Carbyns Cove, Sri Vijaya Puram, Andaman and Nicobar Islands 744106, India",
    lat: 11.6611557,
    lng: 92.75527,
    place: "port-blair",
  },
  {
    id: 23,
    place_types: ["hotel"],
    name: "Silver Sand Sea Princess Beach Resort",
    address:
      "Wandoor Beach, New Wandoor, Sri Vijaya Puram, Andaman and Nicobar Islands 744103, India",
    lat: 11.5986592,
    lng: 92.609367,
    place: "port-blair",
  },
  {
    id: 24,
    place_types: ["hotel"],
    name: "SeaShell, Port Blair",
    address:
      "Marine Hill, Sri Vijaya Puram, Andaman and Nicobar Islands 744101, India",
    lat: 11.6757343,
    lng: 92.739726,
    place: "port-blair",
  },
  {
    id: 25,
    place_types: ["hotel"],
    name: "Coral Reef Hotel & Spa, Port Blair",
    address:
      "Bhathu Basti, Sri Vijaya Puram, Andaman and Nicobar Islands 744105, India",
    lat: 11.6189778,
    lng: 92.7117854,
    place: "port-blair",
  },
  {
    id: 26,
    place_types: ["hotel"],
    name: "TSG Emerald View Hotel & Spa",
    address:
      "#25, MA Rd, Phoenix Bay, Sri Vijaya Puram, Andaman and Nicobar Islands 744102, India",
    lat: 11.6685495,
    lng: 92.7313085,
    place: "port-blair",
  },
  {
    id: 27,
    place_types: ["hotel"],
    name: "Salt Life - A Ocean Front Property",
    address:
      "Sea Shore Road, Haddo, Sri Vijaya Puram, Andaman and Nicobar Islands 744102, India",
    lat: 11.6821954,
    lng: 92.7238647,
    place: "port-blair",
  },
  {
    id: 28,
    place_types: ["hotel"],
    name: "Hotel Atlanta - A Seaview Hotel",
    address:
      "G.B. Pant Road, near Cellular Jail Parking, Atlanta Point, Sri Vijaya Puram, Andaman and Nicobar Islands 744101, India",
    lat: 11.6721653,
    lng: 92.7455293,
    place: "port-blair",
  },
  {
    id: 29,
    place_types: ["hotel"],
    name: "Welcomhotel By ITC Hotels, Port Blair",
    address:
      "Marine Hill, Sri Vijaya Puram, Andaman and Nicobar Islands 744101, India",
    lat: 11.6761772,
    lng: 92.7402004,
    place: "port-blair",
  },
  {
    id: 30,
    place_types: ["hotel"],
    name: "Bayleaf Inn",
    address:
      "Atlanta Point, Sri Vijaya Puram, Andaman and Nicobar Islands 744101, India",
    lat: 11.6710801,
    lng: 92.7440177,
    place: "port-blair",
  },
  {
    id: 31,
    place_types: ["jetty"],
    name: "Phoenix Bay Jetty",
    address: "Sri Vijaya Puram, Andaman and Nicobar Islands 744101, India",
    lat: 11.6733982,
    lng: 92.7343512,
    place: "port-blair",
  },
  {
    id: 32,
    place_types: ["jetty"],
    name: "Haddo Wharf",
    address:
      "Haddo Wharf, Haddo, Sri Vijaya Puram, Andaman and Nicobar Islands 744102, India",
    lat: 11.6829173,
    lng: 92.719202,
    place: "port-blair",
  },
  {
    id: 33,
    place_types: ["jetty"],
    name: "Chatham Jetty",
    address:
      "Haddo, Sri Vijaya Puram, Andaman and Nicobar Islands 744102, India",
    lat: 11.6883571,
    lng: 92.7222562,
    place: "port-blair",
  },
  {
    id: 34,
    place_types: ["jetty"],
    name: "Aberdeen Jetty",
    address:
      "Aberdeen Jetty, Sri Vijaya Puram, Andaman and Nicobar Islands, India",
    lat: 11.6720405,
    lng: 92.7502211,
    place: "port-blair",
  },
  {
    id: 35,
    place_types: ["attraction"],
    name: "Radhanagar Beach (Beach No. 7)",
    address: "Radhanagar Beach, Andaman and Nicobar Islands 744211, India",
    lat: 11.9844552,
    lng: 92.9508454,
    place: "havelock-island",
  },
  {
    id: 36,
    place_types: ["attraction"],
    name: "Kalapathar Beach",
    address: "Kala Pathar Beach, Andaman and Nicobar Islands 744211, India",
    lat: 12.0006111,
    lng: 93.0070952,
    place: "havelock-island",
  },
  {
    id: 37,
    place_types: ["attraction"],
    name: "Govind Nagar Beach (Beach No. 3)",
    address: "Govind Nagar Beach, Andaman and Nicobar Islands 744211, India",
    lat: 12.0306216,
    lng: 93.000842,
    place: "havelock-island",
  },
  {
    id: 38,
    place_types: ["attraction"],
    name: "Vijaynagar Beach (Beach No. 5)",
    address: "Vijay Nagar Beach, Andaman and Nicobar Islands 744211, India",
    lat: 12.0102182,
    lng: 93.0086586,
    place: "havelock-island",
  },
  {
    id: 39,
    place_types: ["attraction"],
    name: "Walking Path To Elephant Beach",
    address: "SH4, Andaman and Nicobar Islands 744211, India",
    lat: 12.0087171,
    lng: 92.9635124,
    place: "havelock-island",
  },
  {
    id: 40,
    place_types: ["hotel"],
    name: "Taj Exotica Resort & Spa, Andamans",
    address:
      "Radha Nagar, Beach Number 7, Havelock Island, Andaman and Nicobar Islands 744211, India",
    lat: 11.983837,
    lng: 92.9559842,
    place: "havelock-island",
  },
  {
    id: 41,
    place_types: ["hotel"],
    name: "TSG Blue Resort & Spa",
    address:
      "Radha Nagar Beach, Havelock Island, Andaman and Nicobar Islands 744211, India",
    lat: 11.9894871,
    lng: 92.9548423,
    place: "havelock-island",
  },
  {
    id: 42,
    place_types: ["hotel"],
    name: "Barefoot at Havelock",
    address:
      "Beach No. 7, Radhanagar Village, Havelock Island, Andaman and Nicobar Islands 744211, India",
    lat: 11.9871751,
    lng: 92.9483748,
    place: "havelock-island",
  },
  {
    id: 43,
    place_types: ["hotel"],
    name: "Havelock Island Beach Resort",
    address:
      "Beach No. 2, Govind Nagar Beach, Havelock Island, Andaman and Nicobar Islands 744211, India",
    lat: 12.0374215,
    lng: 92.987152,
    place: "havelock-island",
  },
  {
    id: 44,
    place_types: ["hotel"],
    name: "Symphony Palms Beach Resort & Spa",
    address:
      "Beach No. 3, Govind Nagar, Havelock, Andaman and Nicobar Islands 744211, India",
    lat: 12.0284596,
    lng: 93.0012988,
    place: "havelock-island",
  },
  {
    id: 45,
    place_types: ["hotel"],
    name: "Dolphin Beach Resort",
    address: "Govind Nagar, Andaman and Nicobar Islands 744211, India",
    lat: 12.0193359,
    lng: 93.0078828,
    place: "havelock-island",
  },
  {
    id: 46,
    place_types: ["hotel"],
    name: "SeaShell, Havelock",
    address:
      "No. 2, Swaraj Dweep, Beach, Govind Nagar, Havelock Island, Andaman and Nicobar Islands 744211, India",
    lat: 12.0357602,
    lng: 92.98783,
    place: "havelock-island",
  },
  {
    id: 47,
    place_types: ["hotel"],
    name: "Silver Sand Beach Resort, Havelock",
    address:
      "No. 5, Vijay Nagar Beach, Swaraj Dweep (Havelock Island), Andaman and Nicobar Islands 744211, India",
    lat: 12.0104239,
    lng: 93.0068355,
    place: "havelock-island",
  },
  {
    id: 48,
    place_types: ["hotel"],
    name: "Tilar Siro, Andamans - CGH Earth",
    address:
      "Beach No. 5, Vijay Nagar, Swaraj Dweep (Havelock Island), Andaman and Nicobar Islands 744211, India",
    lat: 12.0234512,
    lng: 93.0048711,
    place: "havelock-island",
  },
  {
    id: 49,
    place_types: ["hotel"],
    name: "Coral Reef Resort & Spa, Havelock",
    address:
      "No. 5, Vijayanagar, Swaraj Dweep (Havelock Island), Andaman and Nicobar Islands 744211, India",
    lat: 12.0168897,
    lng: 93.0080498,
    place: "havelock-island",
  },
  {
    id: 50,
    place_types: ["jetty"],
    name: "Havelock Jetty",
    address: "Havelock Ferry Ghat, Andaman and Nicobar Islands 744211, India",
    lat: 12.0429471,
    lng: 92.9835984,
    place: "havelock-island",
  },
  {
    id: 51,
    place_types: ["jetty"],
    name: "B3 - Elephant Beach Boarding Point",
    address:
      "Havelock Jetty, Govind Nagar, Swaraj Dweep, Andaman and Nicobar Islands 744211, India",
    lat: 12.0429471,
    lng: 92.9835984,
    place: "havelock-island",
  },
  {
    id: 52,
    place_types: ["restaurant"],
    name: "Full Moon Cafe",
    address: "Havelock No. 3, Andaman and Nicobar Islands 744211, India",
    lat: 12.028268,
    lng: 93.0028705,
    place: "havelock-island",
  },
  {
    id: 53,
    place_types: ["restaurant"],
    name: "Something Different - A Beachside Cafe",
    address:
      "Beach No. 2, behind Havelock Power House, Havelock Island, Andaman and Nicobar Islands 744211, India",
    lat: 12.035727,
    lng: 92.989741,
    place: "havelock-island",
  },
  {
    id: 54,
    place_types: ["restaurant"],
    name: "Anju Coco Resto",
    address:
      "Beach No. 5, Vijay Nagar, Havelock Island, Andaman and Nicobar Islands 744211, India",
    lat: 12.023587,
    lng: 93.00435,
    place: "havelock-island",
  },
  {
    id: 55,
    place_types: ["restaurant"],
    name: "Rajasthani Pure Veg Restaurant (Dhaba)",
    address:
      "SH4, Govind Nagar, Havelock, Andaman and Nicobar Islands 744211, India",
    lat: 12.0284635,
    lng: 93.0007961,
    place: "havelock-island",
  },
  {
    id: 56,
    place_types: ["restaurant"],
    name: "Bonova Cafe And Pub",
    address:
      "Beach Number 2, Govind Nagar, SeaShell Havelock, Havelock Island, Andaman and Nicobar Islands 744211, India",
    lat: 12.035219,
    lng: 92.9884542,
    place: "havelock-island",
  },
  {
    id: 57,
    place_types: ["restaurant"],
    name: "Famous Seafood Restaurant",
    address:
      "5, Vijay Nagar Beach, Havelock, Andaman and Nicobar Islands 744211, India",
    lat: 12.0197214,
    lng: 93.0063371,
    place: "havelock-island",
  },
  {
    id: 58,
    place_types: ["restaurant"],
    name: "Narra",
    address:
      "No. 5, Havelock Island, Vijay Nagar, Andaman and Nicobar Islands 744211, India",
    lat: 12.0200105,
    lng: 93.0067723,
    place: "havelock-island",
  },
  {
    id: 59,
    place_types: ["restaurant"],
    name: "Mohwa The Beach Cafe",
    address:
      "Radhanagar Beach, Havelock, Andaman and Nicobar Islands 744211, India",
    lat: 11.9849529,
    lng: 92.9521489,
    place: "havelock-island",
  },
  {
    id: 60,
    place_types: ["restaurant"],
    name: "Cafe 4",
    address:
      "Shyam Nagar, Swaraj Dweep (Havelock Island), Andaman and Nicobar Islands 744211, India",
    lat: 12.0164827,
    lng: 92.983378,
    place: "havelock-island",
  },
  {
    id: 61,
    place_types: ["restaurant"],
    name: "Barefoot Bar & Brasserie",
    address:
      "No. 1, Havelock Jetty, Govind Nagar, Swaraj Dweep, Andaman and Nicobar Islands 744211, India",
    lat: 12.0418702,
    lng: 92.9820511,
    place: "havelock-island",
  },
  {
    id: 62,
    place_types: ["attraction"],
    name: "Laxmanpur Beach I",
    address:
      "Laxmanpur Beach No. 1, Village Road, Lakshmanpur, Andaman and Nicobar Islands 744104, India",
    lat: 11.847006,
    lng: 93.0156096,
    place: "neil-island",
  },
  {
    id: 63,
    place_types: ["attraction"],
    name: "Laxmanpur Beach II (Natural Bridge)",
    address:
      "Laxmanpur Village, Shaheed Dweep, Andaman and Nicobar Islands, India",
    lat: 11.82485,
    lng: 93.00886,
    place: "neil-island",
  },
  {
    id: 64,
    place_types: ["attraction"],
    name: "Bharatpur Beach",
    address:
      "Neil Island, Bharatpur, Andaman and Nicobar Islands 744104, India",
    lat: 11.8361324,
    lng: 93.034197,
    place: "neil-island",
  },
  {
    id: 65,
    place_types: ["attraction"],
    name: "Sitapur Beach (Sunrise Point)",
    address:
      "Sunrise View Point, Sitapur Beach No. 5, SH6, Sitapur, Andaman and Nicobar Islands 744104, India",
    lat: 11.8204002,
    lng: 93.0615176,
    place: "neil-island",
  },
  {
    id: 66,
    place_types: ["attraction"],
    name: "Ramnagar Beach",
    address: "Ram Nagar, Andaman and Nicobar Islands 744104, India",
    lat: 11.8145031,
    lng: 93.0455465,
    place: "neil-island",
  },
  {
    id: 67,
    place_types: ["jetty"],
    name: "Neil Jetty",
    address: "Neil Island Jetty, Andaman and Nicobar Islands, India",
    lat: 11.8390293,
    lng: 93.0322923,
    place: "neil-island",
  },
  {
    id: 68,
    place_types: ["hotel"],
    name: "TSG Aura Resort",
    address:
      "Beach No. 5, Sitapur Beach, Neil Island (Shaheed Dweep), Andaman and Nicobar Islands 744104, India",
    lat: 11.8207788,
    lng: 93.0609772,
    place: "neil-island",
  },
  {
    id: 69,
    place_types: ["hotel"],
    name: "Symphony Summer Sands, Neil Island",
    address:
      "Ram Nagar Beach, Neil Island, Andaman and Nicobar Islands 744104, India",
    lat: 11.8157514,
    lng: 93.0481029,
    place: "neil-island",
  },
  {
    id: 70,
    place_types: ["hotel"],
    name: "Tango Beach Resort",
    address:
      "Shaheed Dweep, No. 1, Laxmanpur Beach, Lakshmanpur, Andaman and Nicobar Islands 744104, India",
    lat: 11.8435131,
    lng: 93.0184719,
    place: "neil-island",
  },
  {
    id: 71,
    place_types: ["hotel"],
    name: "Silver Sand Beach Resort, Neil Island",
    address:
      "Shaheed Dweep Neil Island, Neil Kendra, Andaman and Nicobar Islands 744104, India",
    lat: 11.8280527,
    lng: 93.0302482,
    place: "neil-island",
  },
  {
    id: 72,
    place_types: ["hotel"],
    name: "SeaShell Samsara, Neil",
    address:
      "Beach, opposite Helipad, Lakshmanpur, Andaman and Nicobar Islands 744104, India",
    lat: 11.8422234,
    lng: 93.0190833,
    place: "neil-island",
  },
  {
    id: 73,
    place_types: ["hotel"],
    name: "Pearl Park Beach Resort & Spa",
    address:
      "Beach No. 1, Lakshmanpur, Andaman and Nicobar Islands 744104, India",
    lat: 11.8455956,
    lng: 93.0143265,
    place: "neil-island",
  },
  {
    id: 74,
    place_types: ["hotel"],
    name: "Peerless Resort",
    address:
      "Corbyns Cove, Carbyns Cove, Sri Vijaya Puram, Andaman and Nicobar Islands 744112, India",
    lat: 11.644018,
    lng: 92.746123,
    place: "neil-island",
  },
  {
    id: 75,
    place_types: ["hotel"],
    name: "Aquays Hotels & Resorts, Neil Island",
    address:
      "No. 3, Beach, Neil Island, Ram Nagar, Andaman and Nicobar Islands 744104, India",
    lat: 11.822908,
    lng: 93.0413245,
    place: "neil-island",
  },
  {
    id: 76,
    place_types: ["hotel"],
    name: "Moon Shine Garden Resort",
    address:
      "Shaheed Dweep, Lakshmanpur, Andaman and Nicobar Islands 744104, India",
    lat: 11.8361119,
    lng: 93.0200733,
    place: "neil-island",
  },
  {
    id: 77,
    place_types: ["hotel"],
    name: "Silver Pearl Beach Resort",
    address:
      "Laxman Pur, Neil Island, Lakshmanpur, Andaman and Nicobar Islands 744104, India",
    lat: 11.8410332,
    lng: 93.023565,
    place: "neil-island",
  },
  {
    id: 78,
    place_types: ["restaurant"],
    name: "Avisa",
    address:
      "Behind Scuba-Yogi Dive Shop, Ram Nagar, Neil Island, Andaman and Nicobar Islands 744104, India",
    lat: 11.8180107,
    lng: 93.0427389,
    place: "neil-island",
  },
  {
    id: 79,
    place_types: ["restaurant"],
    name: "Dugong By SeaShell",
    address:
      "Neil Island, Beach No. 1, Village Road, Lakshmanpur, Andaman and Nicobar Islands 744104, India",
    lat: 11.8396994,
    lng: 93.0244558,
    place: "neil-island",
  },
  {
    id: 80,
    place_types: ["restaurant"],
    name: "Malaca",
    address:
      "Neil Island Beach, opposite Helipad, Lakshmanpur, Andaman and Nicobar Islands 744104, India",
    lat: 11.8422095,
    lng: 93.0189947,
    place: "neil-island",
  },
  {
    id: 81,
    place_types: ["restaurant"],
    name: "Moonlight Restaurant",
    address:
      "Beach No. 5, Beach, Shaheed Dweep, Sitapur, Andaman and Nicobar Islands 744104, India",
    lat: 11.8206429,
    lng: 93.0609677,
    place: "neil-island",
  },
  {
    id: 82,
    place_types: ["restaurant"],
    name: "Garden View Restaurant & Resort",
    address: "Sitapur, Andaman and Nicobar Islands 744104, India",
    lat: 11.8166562,
    lng: 93.051344,
    place: "neil-island",
  },
];

module.exports = locations;
