const locations = [
  {
    id: 1,
    type: "hotel",
    name: "Adhvasaha Beach Spa Resort",
    address: "Rangachang",
    lat: 11.6424704,
    lng: 92.7268864,
    place: "port-blair",
  },
  {
    id: 2,
    type: "hotel",
    name: "Symphony Samudra",
    address: "Chidyatapu",
    lat: 11.5080247,
    lng: 92.7039744,
    place: "port-blair",
  },
  {
    id: 3,
    type: "hotel",
    name: "Sea Cliff",
    address: "South Point",
    lat: 11.6543933,
    lng: 92.7202053,
    place: "port-blair",
  },
  {
    id: 4,
    type: "hotel",
    name: "Sea Princess Beach Resort",
    address: "New Wandoor",
    lat: 11.598726,
    lng: 92.610582,
    place: "port-blair",
  },
  {
    id: 5,
    type: "hotel",
    name: "Sea Shell",
    address: "Marine Hill",
    lat: 11.6757343,
    lng: 92.739726,
    place: "port-blair",
  },
  {
    id: 6,
    type: "hotel",
    name: "Sea Shell Coral Cove",
    address: "Minnie Bay",
    lat: 11.6424704,
    lng: 92.7268864,
    place: "port-blair",
  },
  {
    id: 7,
    type: "hotel",
    name: "Coral Reef",
    address: "Bhathu Basti",
    lat: 11.6422305,
    lng: 92.7268864,
    place: "port-blair",
  },
  {
    id: 8,
    type: "hotel",
    name: "TSG Emerald",
    address: "Phoenix Bay",
    lat: 11.6548583,
    lng: 92.7231932,
    place: "port-blair",
  },
  {
    id: 9,
    type: "hotel",
    name: "Salt Life",
    address: "Haddo",
    lat: 11.6619913,
    lng: 92.7108097,
    place: "port-blair",
  },
  {
    id: 10,
    type: "hotel",
    name: "Mansha Palace",
    address: "Marine Hill",
    lat: 11.6582085,
    lng: 92.7128934,
    place: "port-blair",
  },
  {
    id: 11,
    type: "hotel",
    name: "Atlanta Seaview",
    address: "Atlanta Point",
    lat: 11.672179,
    lng: 92.745544,
    place: "port-blair",
  },
  {
    id: 12,
    type: "hotel",
    name: "Island Cliff",
    address: "Phoenix Bay",
    lat: 11.6650582,
    lng: 92.7228668,
    place: "port-blair",
  },
  {
    id: 13,
    type: "hotel",
    name: "Idhaya",
    address: "Burmanalla",
    lat: 11.5561801,
    lng: 92.7273354,
    place: "port-blair",
  },
  {
    id: 14,
    type: "hotel",
    name: "Olive Hotel & Suites",
    address: "Phoenix Bay",
    lat: 11.6548583,
    lng: 92.7231932,
    place: "port-blair",
  },
  {
    id: 15,
    type: "hotel",
    name: "Sinclairs Bay View",
    address: "South Point",
    lat: 11.6638864,
    lng: 92.7531016,
    place: "port-blair",
  },
  {
    id: 16,
    type: "hotel",
    name: "ITC Welcom",
    address: "Marine Hill",
    lat: 11.6761772,
    lng: 92.7376255,
    place: "port-blair",
  },
  {
    id: 17,
    type: "hotel",
    name: "Andaman Shores Homestay",
    address: "Lamba Line",
    lat: 11.6145,
    lng: 92.7247,
    place: "port-blair",
  },
  {
    id: 18,
    type: "hotel",
    name: "Bayleaf Inn",
    address: "Atlanta Point",
    lat: 11.6710801,
    lng: 92.7414428,
    place: "port-blair",
  },
  {
    id: 19,
    type: "hotel",
    name: "Zostel",
    address: "Phoenix Bay",
    lat: 11.66996,
    lng: 92.731918,
    place: "port-blair",
  },
  {
    id: 20,
    type: "hotel",
    name: "Hornbill Nest",
    address: "Corbyns Cove Rd",
    lat: 11.6472938,
    lng: 92.7510245,
    place: "port-blair",
  },
  {
    id: 21,
    type: "airport",
    name: "VSI Airport",
    address: "Civil Enclave Road",
    lat: 11.64075,
    lng: 92.72931,
    place: "port-blair",
  },
  {
    id: 22,
    type: "attraction",
    name: "Cellular Jail National Memorial",
    address: "Atlanta Point, Port Blair",
    lat: 11.673356,
    lng: 92.750973,
    place: "port-blair",
  },
  {
    id: 23,
    type: "attraction",
    name: "Netaji Subhas Chandra Bose Island Ferry Point",
    address: "Aberdeen Jetty",
    lat: 11.67464,
    lng: 92.75217,
    place: "port-blair",
  },
  {
    id: 24,
    type: "attraction",
    name: "Corbyn's Cove Beach",
    address: "Corbyn's Cove Road",
    lat: 11.64887,
    lng: 92.74973,
    place: "port-blair",
  },
  {
    id: 25,
    type: "attraction",
    name: "Chatham Saw Mill",
    address: "Chatham Island",
    lat: 11.67869,
    lng: 92.73727,
    place: "port-blair",
  },
  {
    id: 26,
    type: "attraction",
    name: "Samudrika Naval Marine Museum",
    address: "Delanipur",
    lat: 11.66697,
    lng: 92.72951,
    place: "port-blair",
  },
  {
    id: 27,
    type: "attraction",
    name: "Anthropological Museum",
    address: "Middle Point",
    lat: 11.66737,
    lng: 92.73443,
    place: "port-blair",
  },
  {
    id: 28,
    type: "attraction",
    name: "Fisheries Museum",
    address: "Rajiv Gandhi Water Sports Complex",
    lat: 11.67514,
    lng: 92.75009,
    place: "port-blair",
  },
  {
    id: 29,
    type: "attraction",
    name: "Forest Museum",
    address: "Chatham Island",
    lat: 11.67802,
    lng: 92.73783,
    place: "port-blair",
  },
  {
    id: 30,
    type: "attraction",
    name: "Jogger's Park",
    address: "Prothrapur",
    lat: 11.62451,
    lng: 92.71602,
    place: "port-blair",
  },
  {
    id: 31,
    type: "attraction",
    name: "Marina Park",
    address: "Rajiv Gandhi Water Sports Complex",
    lat: 11.6757,
    lng: 92.75098,
    place: "port-blair",
  },
  {
    id: 32,
    type: "attraction",
    name: "Gandhi Park",
    address: "Delanipur",
    lat: 11.66822,
    lng: 92.73481,
    place: "port-blair",
  },
  {
    id: 33,
    type: "attraction",
    name: "Science Centre",
    address: "Goodwill Estate",
    lat: 11.66404,
    lng: 92.72887,
    place: "port-blair",
  },
  {
    id: 34,
    type: "attraction",
    name: "Rajiv Gandhi Water Sports Complex",
    address: "Aberdeen",
    lat: 11.67553,
    lng: 92.75098,
    place: "port-blair",
  },
  {
    id: 35,
    type: "jetty",
    name: "Phoenix Bay Jetty",
    address: "Phoenix Bay",
    lat: 11.65486,
    lng: 92.72319,
    place: "port-blair",
  },
  {
    id: 36,
    type: "jetty",
    name: "Haddo Wharf",
    address: "Haddo",
    lat: 11.66664,
    lng: 92.71335,
    place: "port-blair",
  },
  {
    id: 37,
    type: "jetty",
    name: "Chatham Jetty",
    address: "Chatham Island",
    lat: 11.67848,
    lng: 92.73664,
    place: "port-blair",
  },
  {
    id: 38,
    type: "jetty",
    name: "Junglighat Jetty",
    address: "Junglighat",
    lat: 11.65082,
    lng: 92.73183,
    place: "port-blair",
  },
  {
    id: 39,
    type: "jetty",
    name: "Aberdeen Jetty",
    address: "Aberdeen",
    lat: 11.67464,
    lng: 92.75217,
    place: "port-blair",
  },
  {
    id: 40,
    type: "jetty",
    name: "Rajiv Gandhi Water Sports Complex Jetty",
    address: "Aberdeen",
    lat: 11.67553,
    lng: 92.75098,
    place: "port-blair",
  },
  {
    id: 41,
    type: "hotel",
    name: "Lemon Tree Hotel, Port Blair",
    address: "Airport Road",
    lat: 11.64658,
    lng: 92.7209,
    place: "port-blair",
  },
  {
    id: 42,
    type: "hotel",
    name: "Hotel Sentinel",
    address: "Phoenix Bay",
    lat: 11.65723,
    lng: 92.72612,
    place: "port-blair",
  },
  {
    id: 43,
    type: "hotel",
    name: "Hotel Shompen",
    address: "Middle Point",
    lat: 11.66712,
    lng: 92.73354,
    place: "port-blair",
  },
  {
    id: 44,
    type: "hotel",
    name: "Hotel Landmark",
    address: "Goal Ghar",
    lat: 11.66674,
    lng: 92.73258,
    place: "port-blair",
  },
  {
    id: 45,
    type: "hotel",
    name: "Peerless Resort Port Blair",
    address: "Corbyn's Cove",
    lat: 11.65038,
    lng: 92.75289,
    place: "port-blair",
  },
  {
    id: 46,
    type: "hotel",
    name: "TSG Aura Resort",
    address:
      "Beach No. 5, Sitapur Beach, Shaheed Dweep (Neil Island), Port Blair, South Andaman, Andaman and Nicobar Islands, India – 744104",
    lat: 11.8207788,
    lng: 93.0609772,
    place: "neil island",
  },
  {
    id: 47,
    type: "hotel",
    name: "Symphony Summer Sands, Neil Island",
    address:
      "Ram Nagar Beach, Ram Nagar, Shaheed Dweep (Neil Island), Port Blair, South Andaman, Andaman and Nicobar Islands, India – 744104",
    lat: 11.8158,
    lng: 93.0481,
    place: "neil island",
  },
  {
    id: 48,
    type: "hotel",
    name: "Tango Beach Resort",
    address:
      "Beach No. 1, Lakshmanpur Beach, Shaheed Dweep (Neil Island), Port Blair, South Andaman, Andaman and Nicobar Islands, India – 744104",
    lat: 11.8329,
    lng: 93.0135,
    place: "neil island",
  },
  {
    id: 49,
    type: "hotel",
    name: "Pearl Park Beach Resort & SPA",
    address:
      "Beach No. 1, Lakshmanpur Beach, Shaheed Dweep (Neil Island), Port Blair, South Andaman, Andaman and Nicobar Islands, India – 744104",
    lat: 11.8327,
    lng: 93.0118,
    place: "neil island",
  },
  {
    id: 50,
    type: "attraction",
    name: "Bharatpur Beach",
    address: "Bharatpur, Shaheed Dweep (Neil Island)",
    lat: 11.84116,
    lng: 93.03133,
    place: "neil island",
  },
  {
    id: 51,
    type: "attraction",
    name: "Laxmanpur Beach I",
    address: "Laxmanpur Village, Shaheed Dweep",
    lat: 11.83338,
    lng: 93.01295,
    place: "neil island",
  },
  {
    id: 52,
    type: "attraction",
    name: "Laxmanpur Beach II (Natural Bridge)",
    address: "Laxmanpur Village, Shaheed Dweep",
    lat: 11.82485,
    lng: 93.00886,
    place: "neil island",
  },
  {
    id: 53,
    type: "attraction",
    name: "Natural Bridge (Howrah Bridge)",
    address: "Laxmanpur Beach II",
    lat: 11.8249,
    lng: 93.0087,
    place: "neil island",
  },
  {
    id: 54,
    type: "attraction",
    name: "Sitapur Beach (Sunrise Beach)",
    address: "Sitapur Village, Shaheed Dweep",
    lat: 11.82069,
    lng: 93.06125,
    place: "neil island",
  },
  {
    id: 55,
    type: "attraction",
    name: "Ram Nagar Beach",
    address: "Ram Nagar, Shaheed Dweep",
    lat: 11.8158,
    lng: 93.0481,
    place: "neil island",
  },
  {
    id: 56,
    type: "attraction",
    name: "Neil Kendra Village",
    address: "Neil Kendra, Shaheed Dweep",
    lat: 11.82782,
    lng: 93.03477,
    place: "neil island",
  },
  {
    id: 58,
    type: "attraction",
    name: "Neil Island Market",
    address: "Neil Kendra",
    lat: 11.82757,
    lng: 93.03492,
    place: "neil island",
  },
  {
    id: 59,
    type: "attraction",
    name: "Vegetable Farms (Organic Farms)",
    address: "Neil Kendra & surrounding villages",
    lat: 11.8286,
    lng: 93.0349,
    place: "neil island",
  },
  {
    id: 60,
    type: "hotel",
    name: "Taj Exotica Resort & Spa, Andamans",
    address:
      "Radha Nagar, Beach Number 7, Havelock Island, Andaman and Nicobar Islands 744211",
    lat: 11.984243,
    lng: 92.956863,
    place: "havelock-island",
  },
  {
    id: 61,
    type: "hotel",
    name: "TSG Blue Resort & Spa",
    address:
      "Radha Nagar, Beach Number 7, Havelock Island, Andaman and Nicobar Islands 744211",
    lat: 11.989714,
    lng: 92.954893,
    place: "havelock-island",
  },
  {
    id: 62,
    type: "hotel",
    name: "Barefoot at Havelock",
    address:
      "Beach No. 7, Radhanagar Village, Havelock Island, Andaman and Nicobar Islands 744211",
    lat: 11.986947,
    lng: 92.948328,
    place: "havelock-island",
  },
  {
    id: 63,
    type: "hotel",
    name: "De Foret",
    address:
      "No. 7, Radha Nagar Village, Swaraj Dweep, Andaman and Nicobar Islands 744211",
    lat: 12.0047102,
    lng: 92.9597832,
    place: "havelock-island",
  },
  {
    id: 64,
    type: "hotel",
    name: "Symphony Palms Beach Resort & Spa",
    address:
      "Beach No. 3, Govind Nagar, Havelock, Andaman and Nicobar Islands 744211",
    lat: 11.968,
    lng: 92.99011,
    place: "havelock-island",
  },
  {
    id: 65,
    type: "hotel",
    name: "Dolphin Beach Resort",
    address:
      "No. 5, Govind Nagar, Havelock Island (Swaraj Dweep), Andaman and Nicobar Islands 744211",
    lat: 11.9678,
    lng: 93.0035,
    place: "havelock-island",
  },
  {
    id: 66,
    type: "hotel",
    name: "Sea Shell Resort",
    address: "No. 2, Govind Nagar, Andaman and Nicobar Islands 744211",
    lat: 11.9675,
    lng: 92.9902,
    place: "havelock-island",
  },
  {
    id: 67,
    type: "hotel",
    name: "Silver Sand Beach Resort, Havelock",
    address:
      "No. 5, Vijay Nagar Beach, Swaraj Dweep (Havelock Island), Andaman and Nicobar Islands 744211",
    lat: 12.0104239,
    lng: 93.0068355,
    place: "havelock-island",
  },
  {
    id: 68,
    type: "hotel",
    name: "Tilar Siro",
    address:
      "Beach No. 5, Vijay Nagar, Swaraj Dweep (Havelock Island), Andaman and Nicobar Islands 744211",
    lat: 11.9672,
    lng: 92.9984,
    place: "havelock-island",
  },
  {
    id: 69,
    type: "hotel",
    name: "Aquays Hotels & Resorts",
    address:
      "Beach No. 5, Govind Nagar, Havelock Island (Swaraj Dweep), Andaman and Nicobar Islands 744211",
    lat: 11.9806,
    lng: 92.9839,
    place: "havelock-island",
  },
  {
    id: 70,
    type: "hotel",
    name: "Coral Reef Resort & Spa, Havelock",
    address:
      "No. 5, Vijayanagar, Swaraj Dweep (Havelock Island), South Andaman District, Andaman and Nicobar Islands 744211",
    lat: 12.0169,
    lng: 93.0078,
    place: "havelock-island",
  },
  {
    id: 71,
    type: "hotel",
    name: "Sandyy Wavess Beach Resort",
    address: "5 Vijay Nagar, Govind Nagar, Andaman and Nicobar Islands 744211",
    lat: 12.0107,
    lng: 93.0066,
    place: "havelock-island",
  },
  {
    id: 72,
    type: "hotel",
    name: "Ocean Tree Beach Resort & Spa",
    address: "Beach No. 5, Havelock Island, Andaman and Nicobar Islands 744211",
    lat: 12.0165,
    lng: 93.0077,
    place: "havelock-island",
  },
  {
    id: 73,
    type: "attraction",
    name: "Radhanagar Beach (Beach No. 7)",
    address: "Radhanagar, Swaraj Dweep",
    lat: 11.9846,
    lng: 92.9552,
    place: "havelock-island",
  },
  {
    id: 74,
    type: "attraction",
    name: "Elephant Beach",
    address: "West Coast, Swaraj Dweep",
    lat: 12.0067,
    lng: 92.9647,
    place: "havelock-island",
  },
  {
    id: 75,
    type: "attraction",
    name: "Kalapathar Beach",
    address: "Kalapathar Village, Swaraj Dweep",
    lat: 11.9478,
    lng: 93.0286,
    place: "havelock-island",
  },
  {
    id: 76,
    type: "attraction",
    name: "Vijaynagar Beach (Beach No. 5)",
    address: "Vijaynagar, Swaraj Dweep",
    lat: 12.0105,
    lng: 93.0068,
    place: "havelock-island",
  },
  {
    id: 77,
    type: "attraction",
    name: "Govind Nagar Beach (Beach No. 3)",
    address: "Govind Nagar",
    lat: 11.9682,
    lng: 92.991,
    place: "havelock-island",
  },
  {
    id: 78,
    type: "attraction",
    name: "Nemo Reef",
    address: "Govind Nagar Beach",
    lat: 11.9686,
    lng: 92.9918,
    place: "havelock-island",
  },
  {
    id: 79,
    type: "attraction",
    name: "Mangrove Kayaking Point",
    address: "Havelock Mangroves",
    lat: 11.9819,
    lng: 92.9989,
    place: "havelock-island",
  },
  {
    id: 80,
    type: "attraction",
    name: "Lighthouse (Elephant Beach side)",
    address: "Northern Havelock",
    lat: 12.0156,
    lng: 92.9728,
    place: "havelock-island",
  },
  {
    id: 81,
    type: "jetty",
    name: "Makruzz Ferry Terminal",
    address: "Havelock Jetty",
    lat: 11.9849,
    lng: 92.9873,
    place: "havelock-island",
  },
  {
    id: 82,
    type: "jetty",
    name: "Green Ocean Ferry Terminal",
    address: "Havelock Jetty",
    lat: 11.9849,
    lng: 92.9873,
    place: "havelock-island",
  },
  {
    id: 83,
    type: "attraction",
    name: "Havelock Market",
    address: "Govind Nagar",
    lat: 11.9842,
    lng: 92.9878,
    place: "havelock-island",
  },
  {
    id: 84,
    type: "attraction",
    name: "Govind Nagar Junction",
    address: "Govind Nagar",
    lat: 11.9766,
    lng: 92.9897,
    place: "havelock-island",
  },
  {
    id: 85,
    type: "attraction",
    name: "Blue Planet Scuba",
    address: "Govind Nagar",
    lat: 11.9683,
    lng: 92.9913,
    place: "havelock-island",
  },
  {
    id: 86,
    type: "attraction",
    name: "Dive India",
    address: "Govind Nagar",
    lat: 11.9681,
    lng: 92.9911,
    place: "havelock-island",
  },
  {
    id: 87,
    type: "attraction",
    name: "Barefoot Scuba",
    address: "Radhanagar",
    lat: 11.9865,
    lng: 92.9491,
    place: "havelock-island",
  },
  {
    id: 88,
    type: "attraction",
    name: "Ocean Tribe Dive Centre",
    address: "Govind Nagar",
    lat: 11.968,
    lng: 92.9908,
    place: "havelock-island",
  },
  {
    id: 89,
    type: "attraction",
    name: "ScubaLov Dive Centre",
    address: "Govind Nagar",
    lat: 11.9684,
    lng: 92.9916,
    place: "havelock-island",
  },
  {
    id: 90,
    type: "attraction",
    name: "Dive Andaman",
    address: "Govind Nagar",
    lat: 11.9691,
    lng: 92.9922,
    place: "havelock-island",
  },
  {
    id: 91,
    type: "attraction",
    name: "Havelock Bus Stand",
    address: "Govind Nagar",
    lat: 11.9838,
    lng: 92.9875,
    place: "havelock-island",
  },
  {
    id: 92,
    type: "attraction",
    name: "Forest Check Post (Elephant Beach Trek)",
    address: "Near Radhanagar Road",
    lat: 11.9955,
    lng: 92.9733,
    place: "havelock-island",
  },
  {
    id: 93,
    type: "attraction",
    name: "Elephant Beach Trek Entry",
    address: "Havelock Forest Road",
    lat: 11.997,
    lng: 92.9742,
    place: "havelock-island",
  },
  {
    id: 94,
    type: "attraction",
    name: "Beach No. 1",
    address: "Near Jetty",
    lat: 11.9848,
    lng: 92.9876,
    place: "havelock-island",
  },
  {
    id: 95,
    type: "attraction",
    name: "Beach No. 2",
    address: "Govind Nagar",
    lat: 11.9768,
    lng: 92.989,
    place: "havelock-island",
  },
  {
    id: 96,
    type: "attraction",
    name: "Beach No. 3",
    address: "Govind Nagar",
    lat: 11.9682,
    lng: 92.991,
    place: "havelock-island",
  },
  {
    id: 97,
    type: "attraction",
    name: "Beach No. 5",
    address: "Vijaynagar",
    lat: 12.0105,
    lng: 93.0068,
    place: "havelock-island",
  },
  {
    id: 98,
    type: "attraction",
    name: "Beach No. 7 (Radhanagar Beach)",
    address: "Radhanagar",
    lat: 11.9846,
    lng: 92.9552,
    place: "havelock-island",
  },
  {
    id: 99,
    type: "hotel",
    name: "Haywizz Havelock Island Resort",
    address:
      "No. 1, Govind Nagar, Havelock Island (Swaraj Dweep), Port Blair Tehsil, South Andaman District, Andaman and Nicobar Islands 744211",
    lat: 11.9722,
    lng: 92.9904,
    place: "havelock-island",
  },
];

module.exports = locations;
